#!/usr/bin/env bash
set -e

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
WORK_DIR=$(realpath "${SCRIPT_DIR}/..")
WEB_DIR="${WORK_DIR}/web"
BUILD_DIR="${WORK_DIR}/build"
WEB_BUILD_DIR="${BUILD_DIR}/web"
MDI_DIR="${WEB_DIR}/node_modules/@material-design-icons/svg/outlined"
ANDROID_ASSETS_DIR="${WORK_DIR}/android/src/main/assets"

echo
echo "======================== Building Web app =========================="
echo

mkdir -p ${WEB_BUILD_DIR}
cd ${WEB_DIR}
npm install
npx esbuild --bundle --outdir=${WEB_BUILD_DIR} main.js

echo
echo "====================== Building Android app ========================"
echo

# Include web app into Android project
mkdir -p ${ANDROID_ASSETS_DIR}/web
cp \
    index.html \
    ${WEB_DIR}/node_modules/bootstrap/dist/css/bootstrap.css \
    ${MDI_DIR}/file_download.svg \
    ${MDI_DIR}/file_upload.svg \
    ${WEB_BUILD_DIR}/main.js \
    ${ANDROID_ASSETS_DIR}/web

cd "${WORK_DIR}"
gradle \
    -Dorg.gradle.project.android.aapt2FromMavenOverride=${AAPT2:?} \
    build
