#!/usr/bin/env bash
set -e

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
WORK_DIR=$(realpath "${SCRIPT_DIR}/..")

# Include web app into Android project
mkdir -p "${WORK_DIR}/android/src/main/assets"
cp -r "${WORK_DIR}/web" "${WORK_DIR}/android/src/main/assets/web"

cd "${WORK_DIR}"
gradle \
    -Dorg.gradle.project.android.aapt2FromMavenOverride=${AAPT2:?} \
    build
