#!/usr/bin/env bash
set -e

SCRIP_DIR=$(dirname "$(readlink -f "$0")")
WORK_DIR=$(realpath "${SCRIP_DIR}/..")

cd "${WORK_DIR}"
gradle \
    -Dorg.gradle.project.android.aapt2FromMavenOverride=${AAPT2:?} \
    build
